"""
Nifty Midcap 150 — Monthly Top 10 Telegram Alert
Sends top 10 stocks by 1-year return to Telegram
"""

import csv
import json
import os
import sys
import urllib.request
import urllib.parse
from datetime import datetime, timedelta

import pandas as pd
import yfinance as yf


TELEGRAM_TOKEN = "8789106162:AAF2Ly4cqYyabNqhD5oyjdiomkMrIW5Ef7Y"
TELEGRAM_CHAT_ID = "763520679"
CSV_PATH = r"C:\Users\prave\Downloads\ind_niftymidcap150list.csv"


def send_telegram(message: str):
    url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
    data = urllib.parse.urlencode({
        "chat_id": TELEGRAM_CHAT_ID,
        "text": message,
        "parse_mode": "HTML",
    }).encode("utf-8")
    req = urllib.request.Request(url, data=data)
    with urllib.request.urlopen(req, timeout=15) as resp:
        result = json.loads(resp.read())
        if not result.get("ok"):
            print(f"Telegram error: {result}")
        return result


def load_stock_list(csv_path: str) -> list[tuple[str, str]]:
    stocks = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            sym = row.get("Symbol", "").strip()
            name = row.get("Company Name", "").strip()
            if sym:
                stocks.append((sym, name))
    return stocks


def get_returns(symbol: str) -> dict | None:
    ticker = f"{symbol}.NS"
    try:
        end_date = datetime.now()
        start_date = end_date - timedelta(days=1830)
        data = yf.download(
            ticker,
            start=start_date.strftime("%Y-%m-%d"),
            end=end_date.strftime("%Y-%m-%d"),
            progress=False,
            auto_adjust=False,
        )
        if data is None or data.empty:
            return None

        closes = data["Close"]
        if isinstance(closes, pd.DataFrame):
            closes = closes.iloc[:, 0]
        closes = closes.dropna()

        if len(closes) < 2:
            return None

        last_date = closes.index[-1]
        last_price = float(closes.iloc[-1])

        periods = {
            "1W": 7,
            "1M": 30,
            "3M": 91,
            "1Y": 365,
        }

        results = {}
        for label, days in periods.items():
            target_date = last_date - timedelta(days=days)
            available = closes[closes.index <= target_date]
            if available.empty:
                results[label] = None
            else:
                first = float(available.iloc[-1])
                if first == 0:
                    results[label] = None
                else:
                    results[label] = round(((last_price - first) / first) * 100, 2)

        results["current_price"] = round(last_price, 2)
        return results
    except Exception:
        return None


def format_alert(top10: pd.DataFrame, total_stocks: int, data_date: str) -> str:
    lines = []
    lines.append(f"<b>NIFTY MIDCAP 150 - TOP 10 by 1Y Return</b>")
    lines.append(f"Date: {data_date}")
    lines.append(f"Stocks Analyzed: {total_stocks}")
    lines.append("")

    for i, (_, row) in enumerate(top10.iterrows(), 1):
        sym = row["symbol"]
        name = row["name"]
        price = row["current_price"]
        ret_1w = row.get("1W")
        ret_1m = row.get("1M")
        ret_3m = row.get("3M")
        ret_1y = row.get("1Y")

        ret_1w_s = f"{ret_1w:+.1f}%" if ret_1w is not None else "N/A"
        ret_1m_s = f"{ret_1m:+.1f}%" if ret_1m is not None else "N/A"
        ret_3m_s = f"{ret_3m:+.1f}%" if ret_3m is not None else "N/A"
        ret_1y_s = f"{ret_1y:+.1f}%" if ret_1y is not None else "N/A"

        lines.append(f"<b>{i}. {sym}</b> ({name})")
        lines.append(f"   Price: Rs.{price:,.2f}")
        lines.append(f"   1W: {ret_1w_s} | 1M: {ret_1m_s} | 3M: {ret_3m_s} | 1Y: <b>{ret_1y_s}</b>")
        lines.append("")

    lines.append(f"<i>Auto-generated by Nifty Midcap Alert Bot</i>")
    return "\n".join(lines)


def main():
    if not os.path.exists(CSV_PATH):
        print(f"CSV not found: {CSV_PATH}")
        sys.exit(1)

    stocks = load_stock_list(CSV_PATH)
    print(f"Loaded {len(stocks)} stocks. Fetching data...\n")

    results = []
    total = len(stocks)
    for i, (sym, name) in enumerate(stocks, 1):
        print(f"[{i}/{total}] {sym}...", end="", flush=True)
        data = get_returns(sym)
        if data:
            row = {"symbol": sym, "name": name, **data}
            results.append(row)
            ret_1y = data.get("1Y")
            print(f" {ret_1y:+.2f}%" if ret_1y is not None else " done")
        else:
            print(" skipped")

    if not results:
        print("\nNo data retrieved.")
        sys.exit(1)

    df = pd.DataFrame(results)
    period_cols = ["1W", "1M", "3M", "1Y"]
    df_sorted = df.sort_values("1Y", ascending=False, na_position="last").reset_index(drop=True)
    top10 = df_sorted.head(10)

    data_date = datetime.now().strftime("%Y-%m-%d %H:%M")
    alert_msg = format_alert(top10, len(results), data_date)

    print("\n--- Telegram Message ---")
    print(alert_msg)
    print("--- Sending to Telegram ---")

    result = send_telegram(alert_msg)
    if result.get("ok"):
        print("Message sent successfully!")
    else:
        print("Failed to send message.")

    top10[["symbol", "name", "current_price", "1W", "1M", "3M", "1Y"]].to_csv(
        "nifty_midcap_top10_monthly.csv", index=False
    )
    print("Saved to: nifty_midcap_top10_monthly.csv")


if __name__ == "__main__":
    main()
